<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="450" started-at="2019-11-21T09:20:57Z" finished-at="2019-11-21T09:20:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="450" started-at="2019-11-21T09:20:57Z" finished-at="2019-11-21T09:20:57Z">
      <class name="testRunner.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:testRunner.TestRunner@2812cbfa]" name="setUpClass" is-config="true" duration-ms="374" started-at="2019-11-21T14:50:57Z" finished-at="2019-11-21T14:50:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="SKIP" signature="feature(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:testRunner.TestRunner@2812cbfa]" name="feature" duration-ms="0" started-at="2019-11-21T14:50:57Z" data-provider="Features" finished-at="2019-11-21T14:50:57Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Method public void testRunner.TestRunner.feature(cucumber.api.testng.PickleEventWrapper,cucumber.api.testng.CucumberFeatureWrapper) throws java.lang.Throwable requires a @DataProvider named : Features]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Method public void testRunner.TestRunner.feature(cucumber.api.testng.PickleEventWrapper,cucumber.api.testng.CucumberFeatureWrapper) throws java.lang.Throwable requires a @DataProvider named : Features
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:263)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:419)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1276)
	at org.testng.internal.Invoker.createParameters(Invoker.java:991)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1081)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:testRunner.TestRunner@2812cbfa]" name="tearDownClass" is-config="true" duration-ms="39" started-at="2019-11-21T14:50:57Z" finished-at="2019-11-21T14:50:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- testRunner.TestRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
